name: Test

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Build
        run: |
          go build
      - name: test & coverage report creation
        run: |
          go test common.go -mod=readonly -timeout 5m -short -race -coverprofile=coverage.txt -covermode=atomic
          go test common.go -mod=readonly -timeout 5m
      - uses: codecov/codecov-action@v4.5.0
        with:
          file: ./coverage.txt
          fail_ci_if_error: true
