name: Test
on:
  push:
  pull_request:

jobs:

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: test & coverage report creation
        run: |
          go test common.go -mod=readonly -timeout 5m -short -race -coverprofile=coverage.txt -covermode=atomic
          go test common.go -mod=readonly -timeout 5m
